name = "khatta"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "all-rounder"
database_id = "7f04b9f8-97ce-47cc-9ea7-b10f9e8388a6"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "khata-proofs"

[vars]
ADMIN_EMAIL = "aua4820@gmail.com"
APP_URL = "https://khatta.pages.dev"
BREVO_FROM_EMAIL = "info@wellcart.pk"
BREVO_FROM_NAME = "KhataBook"
PayFast_BASE_URL = "https://ipg1.apps.net.pk"
PAYFAST_MERCHANT_ID = "22554"
PAYFAST_STORE_ID = "22554-1J41OFM7RJ_V"
