name = "khatta"
pages_build_output_dir = "public"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "all-rounder"
database_id = "7f04b9f8-97ce-47cc-9ea7-b10f9e8388a6"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "khata-proofs"

[vars]
APP_URL = "https://khatta.pages.dev"
BREVO_FROM_NAME = "KhataBook"
PayFast_BASE_URL = "https://ipg1.apps.net.pk"
